name: Feature -> Unstable

on:    
  push:
    branches:
     TEST_Feature_dev

jobs:
  PoolRequest:    
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        
        - name: Create Pull Request
          id: PoolRequest
          uses: repo-sync/pull-request@v2
          with:
            destination_branch: "main"
            github_token: ${{ secrets.GITHUB_TOKEN }}
            
        - uses: hmarr/auto-approve-action@v2
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            pull-request-number: ${{ steps.PoolRequest.outputs.pr_number}}
        
