name: Feature -> Unstable

on:    
  push:
    branches:
     '*_Feature_dev'

jobs:
  PoolRequest:    
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        
        - name: Create Pull Request
          id: open-pr
          uses: repo-sync/pull-request@v2
          with:
            destination_branch: "Develop_FR_Unstable"
            github_token: ${{ secrets.GITHUB_TOKEN }}
        
        - name: Echo Pr
          run: echo ${{steps.open-pr.outputs.pr_number}}
  
        - name: Approve
          if: ${{steps.open-pr.outputs.pr_number}}
          uses: juliangruber/merge-pull-request-action@v1
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            number: ${{steps.open-pr.outputs.pr_number}}
            
