name: Feature -> Unstable

on:    
  push:
    branches:
     TEST_Feature_dev

jobs:
  PoolRequest:    
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        
        - name: Create Pull Request
          id: Open-Pool
          uses: repo-sync/pull-request@v2
          with:
            destination_branch: "Develop_FR_Unstable"
            github_token: ${{ secrets.GITHUB_TOKEN }}
            pr_reviewer: "gmarolla"
            pr_assignee: "gmarolla"
        
        - name: Echo Version
          run: echo ${{steps.Open-Pool.outputs.pr_number}}
  
        - name: Approve
          uses: hmarr/auto-approve-action@v2
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            pull-request-number: ${{ steps.Open-Pool.outputs.pr_number }}
